name: publication pipeline
on:
  push:
    branches:
      - master
jobs:
  publish:
    env:
      INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
      token: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        env:
          token: ${{ secrets.NPM_TOKEN }}

