name: publication pipeline
on:
  push:
    branches:
      - master
jobs:
  publish:
    env:
      INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}
      token: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - run: npm install
      - run: npm test
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.TEST_SECRET }}
      - run: |
          echo "$SUPER_SECRET"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: "some-value"

