name: publication pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run lint
      - name: publish
        image: node:14
        environment:
          NPM_TOKEN:
            from_secret: NPM_PUBLICATION_TOKEN
        commands:
        - echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > .npmrc
        - npm publish

